### PR TITLE
Add Chris to speakers

### PR DESCRIPTION
**Pull request by davidroberts63**
Latest speaker addition

### CODE REVIEW

**Comment by davidroberts63** [comment]
post
post screenshot
home
home screenshot
home
home screenshot
post
post screenshot

**Comment by the-simian** [comment]
these automatic git hooks are cool

**Comment by davidroberts63** [comment]
Yeah. I'm going to work in making what I've done into NPM packages for others to use.

-----Original Message-----

**Comment by matthewreily** [comment]
That would be awesome @davidroberts63

**Pull request merged**
