### PR TITLE
December 2015 meeting

### PR DESCRIPTION
**Pull request by davidroberts63**
Lightning talks

### CODE REVIEW

**Comment by davidroberts63** [comment]
home
home screenshot
post
post screenshot
home
home screenshot
post
post screenshot

**Comment by the-simian** [comment]
:+1:

**Comment by davidroberts63** [comment]
Working on a post going over how that screenshot process works. Should be up in a day or two.

-----Original Message-----

**Comment by the-simian** [comment]
Oh did you automate that? I noticed some of the css in the images above were different than the site, so I suspected some automation

**Comment by davidroberts63** [comment]
Yeah. Fork it make a new post and pull. You'll see screenshots show up in a few minutes. 

Really, try it. I just won't merge it.

-----Original Message-----

**Comment by the-simian** [comment]
Cool beans. I look forward to the post, then we could maybe implement this on some of the other projects we have

**Comment by davidroberts63** [comment]
post
post screenshot
post
post screenshot
home
home screenshot
home
home screenshot

**Pull request merged**
